name: laravel-tests

# évènement qui déclenche les tests
on:
  push:
    branches: [ main ]
    paths:
      - 'tests/Unit/ProductTest.php'
      - 'tests/Feature/PostProductTest.php'
  pull_request:
    branches: [ main ]


# définition répertoire de travail
defaults:
  run:
    working-directory: ./mes_tests

# variable d'environnement
env:
  <ma variable d'env>: <ma valeur>
  php_version: 8.3

jobs:

  test:
    runs-on: ubuntu-latest
    concurrency:
      group: laravel-tests-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    # récupération du code source
    steps:

      - name: Checkout project
        uses: actions/checkout@v3

      - name: Initialize PHP ${{ env.php_version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php_version }}
          coverage: pcov

      # installation des dépendances
      - name: Composer install
        run: |
          composer validate --strict
          composer install --optimize-autoloader --no-interaction --prefer-dist

      # lancement des tests
      - name: Test
        run: php artisan test
