name: laravel-tests

# évènement qui déclenche les tests
on:
  push:
    branches: [ main ]

# variable d'environnement
env:
  php_version: 8.3

jobs:

  test:
    runs-on: ubuntu-latest
    concurrency:
      group: laravel-tests-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    # récupération du code source et clonage projet
    steps:

      - name: Checkout project
        uses: actions/checkout@v3

      - name: Initialize PHP ${{ env.php_version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php_version }}
          coverage: pcov

      # installation des dépendances
      - name: Composer install
        run: |
          composer validate --strict
          composer install --optimize-autoloader --no-interaction --prefer-dist

      # lancement des tests
      - name: Test
        run: php artisan test
